### ISSUE TITLE
docker-composeメッモ

### ISSUE THREAD

**Issue by akiumikin** [akiumikin/next_js#1]
``` yml
version: '3.7'

services:
  rails:
    build: .
    image: app_rails:1.3 # latest_update: webpack導入に合わせたリファクタリング
    container_name: app_rails
    tty: true
    stdin_open: true
    ports:
      - 4000:3000
    environment:
      RAILS_ENV: development
      APP_DATABASE_USER_NAME: root
      APP_DATABASE_PASSWORD: P@ssw0rd
      APP_DATABASE_HOST: mysql
    depends_on:
      - mysql
      - webpack
    volumes:
      - ./:/var/www/app
      - vendor:/var/www/app/vendor
      - ~/.ssh:/root/.ssh
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle && bin/rails db:create db:migrate db:seed && bundle exec rails server -b 0.0.0.0'"

  webpack:
    build: .
    image: app_webpack:1.0 # latest_update: add webpack container
    container_name: app_webpack
    tty: true
    stdin_open: true
    ports:
      - 8200:8200
    environment: {}
    volumes:
      - ./:/var/www/app
    command: "bash -c 'npm i && npm run start'"

  mysql:
    image: mysql:5.7.22 # latest_update: add mysql container
    container_name: app_mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 3400:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8

volumes:
  vendor:
    driver: 'local'
  mysql-data:
    name: app_mysql
```
